### ISSUE TITLE
Поправить верстку

### ISSUE THREAD

**Issue by techwri** [techwri/techwritersru#14]
7 и 8 пункт слетела верстка

 on page /ru/technical_writer/working_in_team/first_days.htmlYour issue content here.

**Comment by techwri** [comment]
поправлено, [проверить](http://techwriters.ru/ru/technical_writer/working_in_team/onboarding.html) в релизе и закрыть

**Comment by dunmaksim** [comment]
Это потому что 4 пробела вместо 3. По идее, эту проблему должен закрыть мой PR: https://github.com/techwri/techwritersru/pull/32

**Comment by techwri** [comment]
да, решено
